/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ALUNO
 */
public class cadastroPlano2 extends javax.swing.JFrame {

    /**
     * Creates new form cadastroPlano2
     */
    public cadastroPlano2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taxaadesao = new javax.swing.JLabel();
        cadastrodeplano = new javax.swing.JLabel();
        taxa = new javax.swing.JTextField();
        statusplano = new javax.swing.JLabel();
        nomeplano = new javax.swing.JLabel();
        ativodesetivo = new javax.swing.JComboBox<>();
        driscricaodoplano = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        plano = new javax.swing.JTextField();
        mudar = new javax.swing.JButton();
        apaga = new javax.swing.JButton();
        valormensal = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        nomeparaplano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taxaadesao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taxaadesao.setText("Taxa de Adesão");
        jPanel1.add(taxaadesao, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 209, -1, -1));

        cadastrodeplano.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cadastrodeplano.setText("Cadastro de Plano ");
        jPanel1.add(cadastrodeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 31, -1, -1));
        jPanel1.add(taxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 232, 85, -1));

        statusplano.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statusplano.setText("Status do Plano");
        jPanel1.add(statusplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 272, -1, -1));

        nomeplano.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nomeplano.setText("Nome de Plano");
        jPanel1.add(nomeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 71, 97, -1));

        ativodesetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Desativado" }));
        jPanel1.add(ativodesetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 295, -1, -1));

        driscricaodoplano.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        driscricaodoplano.setText("Discrição do plano");
        jPanel1.add(driscricaodoplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 140, -1, -1));

        salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salvar.setText("Salvar");
        jPanel1.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 372, -1, -1));
        jPanel1.add(plano, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 169, 338, -1));

        mudar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mudar.setText("Editar");
        jPanel1.add(mudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 372, -1, -1));

        apaga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        apaga.setText("Excluir");
        jPanel1.add(apaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 372, -1, -1));

        valormensal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valormensal.setText("Valor Mensal");
        jPanel1.add(valormensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 209, -1, -1));
        jPanel1.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 232, 76, -1));

        nomeparaplano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeparaplanoActionPerformed(evt);
            }
        });
        jPanel1.add(nomeparaplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 340, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Cadastro (2).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeparaplanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeparaplanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeparaplanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroPlano2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroPlano2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroPlano2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroPlano2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroPlano2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apaga;
    private javax.swing.JComboBox<String> ativodesetivo;
    private javax.swing.JLabel cadastrodeplano;
    private javax.swing.JLabel driscricaodoplano;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mudar;
    private javax.swing.JTextField nomeparaplano;
    private javax.swing.JLabel nomeplano;
    private javax.swing.JTextField plano;
    private javax.swing.JTextField preco;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel statusplano;
    private javax.swing.JTextField taxa;
    private javax.swing.JLabel taxaadesao;
    private javax.swing.JLabel valormensal;
    // End of variables declaration//GEN-END:variables
}
