/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class Caixa extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public Caixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiasPagamentos = new javax.swing.JTabbedPane();
        painelRelatorio = new javax.swing.JPanel();
        painelCaixa = new javax.swing.JPanel();
        labelCaixa = new javax.swing.JLabel();
        rotuloDoCiente = new javax.swing.JLabel();
        nomeCiente = new javax.swing.JTextField();
        seleconarMaquina = new javax.swing.JComboBox<>();
        maquinas = new javax.swing.JLabel();
        formaDoPagamento = new javax.swing.JLabel();
        mesaDeMaquinas = new javax.swing.JScrollPane();
        tabelaDasMaquinas = new javax.swing.JTable();
        imagem = new javax.swing.JLabel();
        tipoDeServiços = new javax.swing.JLabel();
        selecionarTipoDeServiço = new javax.swing.JComboBox<>();
        pagamento = new javax.swing.JComboBox<>();
        valor = new javax.swing.JLabel();
        valorPagor = new javax.swing.JComboBox<>();
        botaoLigar = new javax.swing.JToggleButton();
        leiboDeImagemDeFundor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Financeiro");

        painelCaixa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCaixa.setText("Caixa");
        painelCaixa.add(labelCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 6, 50, -1));

        rotuloDoCiente.setText("Nome Cliente:");
        painelCaixa.add(rotuloDoCiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 53, -1, -1));
        painelCaixa.add(nomeCiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 356, -1));

        seleconarMaquina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Play 1", "Play 2", "Play 3", "PC 1", "PC 2", "PC 3", "Simulador 1", "Simulador 2", "Simulador 3" }));
        seleconarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleconarMaquinaActionPerformed(evt);
            }
        });
        painelCaixa.add(seleconarMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 118, -1, -1));

        maquinas.setText("Maquina:");
        painelCaixa.add(maquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 124, 64, -1));

        formaDoPagamento.setText("Forma de Pagamento");
        painelCaixa.add(formaDoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 201, -1, -1));

        tabelaDasMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PC Game", "Consoles", "Simulador"
            }
        ));
        mesaDeMaquinas.setViewportView(tabelaDasMaquinas);

        painelCaixa.add(mesaDeMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, 343));

        imagem.setBackground(new java.awt.Color(0, 0, 0));
        imagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Blusa Neon (1).jpg")); // NOI18N
        painelCaixa.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 248));

        tipoDeServiços.setText("Tipo de Serviço");
        painelCaixa.add(tipoDeServiços, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 81, 85, -1));

        selecionarTipoDeServiço.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Bonificação", "Plano\t\t\t", "Teste" }));
        painelCaixa.add(selecionarTipoDeServiço, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 78, 98, -1));

        pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Cartão", "Dinheiro" }));
        painelCaixa.add(pagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 198, 106, -1));

        valor.setText("Valor");
        painelCaixa.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 161, 40, -1));

        valorPagor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20 minutos - R$ 20,00", "30 minutos - R$ 40,00", "60 minutos - R$ 60,00", "Plano Amador- R$ 120,00", "Plano Profissional - R$  250,00", "Plano Lendário  - R$ 550,00" }));
        valorPagor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPagorActionPerformed(evt);
            }
        });
        painelCaixa.add(valorPagor, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 158, -1, -1));

        botaoLigar.setText("Ligar Maquinar");
        painelCaixa.add(botaoLigar, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 371, -1, -1));

        leiboDeImagemDeFundor.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Cadastro (2).png")); // NOI18N
        painelCaixa.add(leiboDeImagemDeFundor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, -150, 1370, 770));

        javax.swing.GroupLayout painelRelatorioLayout = new javax.swing.GroupLayout(painelRelatorio);
        painelRelatorio.setLayout(painelRelatorioLayout);
        painelRelatorioLayout.setHorizontalGroup(
            painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelRelatorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        painelRelatorioLayout.setVerticalGroup(
            painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(painelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelRelatorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        guiasPagamentos.addTab("Relatorio", painelRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiasPagamentos))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guiasPagamentos)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seleconarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleconarMaquinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleconarMaquinaActionPerformed

    private void valorPagorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPagorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPagorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoLigar;
    private javax.swing.JLabel formaDoPagamento;
    private javax.swing.JTabbedPane guiasPagamentos;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel labelCaixa;
    private javax.swing.JLabel leiboDeImagemDeFundor;
    private javax.swing.JLabel maquinas;
    private javax.swing.JScrollPane mesaDeMaquinas;
    private javax.swing.JTextField nomeCiente;
    private javax.swing.JComboBox<String> pagamento;
    private javax.swing.JPanel painelCaixa;
    private javax.swing.JPanel painelRelatorio;
    private javax.swing.JLabel rotuloDoCiente;
    private javax.swing.JComboBox<String> selecionarTipoDeServiço;
    private javax.swing.JComboBox<String> seleconarMaquina;
    private javax.swing.JTable tabelaDasMaquinas;
    private javax.swing.JLabel tipoDeServiços;
    private javax.swing.JLabel valor;
    private javax.swing.JComboBox<String> valorPagor;
    // End of variables declaration//GEN-END:variables
}
