/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.CadastroDeFuncionarioModel;

/**
 *
 * @author ALUNO
 */
public class Casdastrodefuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Casdastrodefuncionario
     */
    public Casdastrodefuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nomecompleto = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        cpfdigitando = new javax.swing.JFormattedTextField();
        datadenacimento = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        genero = new javax.swing.JLabel();
        opcao = new javax.swing.JComboBox<>();
        email = new javax.swing.JLabel();
        falaoseeuemail = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        senhadigitada = new javax.swing.JPasswordField();
        entre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        fone = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomecompleto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomecompleto.setText("Nome completo");
        jPanel1.add(nomecompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, -1, 24));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 97, 262, -1));

        cpf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cpf.setText("CPF");
        jPanel1.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, -1, -1));

        try {
            cpfdigitando.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfdigitando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfdigitandoActionPerformed(evt);
            }
        });
        jPanel1.add(cpfdigitando, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 173, 115, -1));

        datadenacimento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        datadenacimento.setText("Data de nacimento");
        jPanel1.add(datadenacimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, -1, -1));

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 132, 84, -1));

        genero.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        genero.setText("Genêro");
        jPanel1.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 172, 71, -1));

        opcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Masculino", "Feminino" }));
        jPanel1.add(opcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 173, -1, -1));

        email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        email.setText("E-mail");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 207, -1, -1));
        jPanel1.add(falaoseeuemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 208, 340, -1));

        senha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        senha.setText("Senha");
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, -1, -1));
        jPanel1.add(senhadigitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 243, 161, -1));

        entre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        entre.setText("Cadastra");
        entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreActionPerformed(evt);
            }
        });
        jPanel1.add(entre, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 286, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText(" Cadastro de Funcionário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 17, -1, 47));

        editar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        editar.setText("Editar");
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 286, -1, -1));

        excluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        excluir.setText("Excluir");
        jPanel1.add(excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 286, -1, -1));

        fone.setText("Fone");
        jPanel1.add(fone, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 135, -1, -1));

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        jPanel1.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 132, 114, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Cadastro (2).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-13, -4, 570, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nomeActionPerformed

    private void entreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreActionPerformed
        // TODO add your handling code here:
        
        // criar um funconario da classe
        CadastroDeFuncionarioModel funcionario = new CadastroDeFuncionarioModel();
        // cadastrar os dados dentro da classe funcionário
        funcionario.setNomecompleto(nomecompleto.getText());
        funcionario.setDatadenacimento(datadenacimento.getText());
        funcionario.setFone(fone.getText());
       
        //captutar dados da combobox
        funcionario.setOpcao((String)opcao.getSelectedItem());
        
        // capturar dados ao campo password fienld
        funcionario.setSenha((String)senhadigitada.getPassword().toString());
        
        //capturar os dados dos campos formatados
        funcionario.setCpf(cpfdigitando.getText());
        funcionario.setDatadenacimento(data.getText());
        
        
    }//GEN-LAST:event_entreActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void cpfdigitandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfdigitandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfdigitandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casdastrodefuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casdastrodefuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casdastrodefuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casdastrodefuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casdastrodefuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpf;
    private javax.swing.JFormattedTextField cpfdigitando;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JLabel datadenacimento;
    private javax.swing.JButton editar;
    private javax.swing.JLabel email;
    private javax.swing.JButton entre;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField falaoseeuemail;
    private javax.swing.JLabel fone;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomecompleto;
    private javax.swing.JComboBox<String> opcao;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField senhadigitada;
    private javax.swing.JFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables
}
