/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new javax.swing.JPanel();
        campoCpf1 = new javax.swing.JTextField();
        campoCpf = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        varivelSenha = new javax.swing.JLabel();
        butomLogin = new javax.swing.JButton();
        paonelLayout1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoCpf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpf1ActionPerformed(evt);
            }
        });
        painel1.add(campoCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 290, -1));

        campoCpf.setBackground(new java.awt.Color(255, 255, 255));
        campoCpf.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        campoCpf.setText("CPF");
        painel1.add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 200, 20));

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        painel1.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 290, -1));

        varivelSenha.setBackground(new java.awt.Color(255, 255, 255));
        varivelSenha.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        varivelSenha.setText("Senha");
        painel1.add(varivelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, 60));

        butomLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        butomLogin.setText("Login");
        butomLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butomLoginActionPerformed(evt);
            }
        });
        painel1.add(butomLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        paonelLayout1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Login (2).png")); // NOI18N
        painel1.add(paonelLayout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 710));

        getContentPane().add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpf1ActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void butomLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butomLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butomLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butomLogin;
    private javax.swing.JLabel campoCpf;
    private javax.swing.JTextField campoCpf1;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JPanel painel1;
    private javax.swing.JLabel paonelLayout1;
    private javax.swing.JLabel varivelSenha;
    // End of variables declaration//GEN-END:variables
}
