/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoIconeCliente = new javax.swing.JButton();
        botaoIconeFuncionarios = new javax.swing.JButton();
        botaoIconePlanos = new javax.swing.JButton();
        botaoIconeCaixa = new javax.swing.JButton();
        botaoIconeMaquinas = new javax.swing.JButton();
        botaoCliente = new javax.swing.JButton();
        botaoFuncionarios = new javax.swing.JButton();
        botaoPlanos = new javax.swing.JButton();
        botaoMaquinas = new javax.swing.JButton();
        botaoCaixa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoIconeCliente.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\NewBitNexus\\Imagens Menu\\client.png")); // NOI18N
        jPanel1.add(botaoIconeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 136, 115, 96));

        botaoIconeFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeFuncionarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\NewBitNexus\\Imagens Menu\\group.png")); // NOI18N
        jPanel1.add(botaoIconeFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 119, 96));

        botaoIconePlanos.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconePlanos.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\NewBitNexus\\Imagens Menu\\planning.png")); // NOI18N
        botaoIconePlanos.setText("\n");
        jPanel1.add(botaoIconePlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 136, -1, 96));

        botaoIconeCaixa.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeCaixa.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\NewBitNexus\\Imagens Menu\\budget.png")); // NOI18N
        jPanel1.add(botaoIconeCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 356, 102, 101));

        botaoIconeMaquinas.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeMaquinas.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\NewBitNexus\\Imagens Menu\\monitoring.png")); // NOI18N
        jPanel1.add(botaoIconeMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 356, 109, 101));

        botaoCliente.setBackground(new java.awt.Color(102, 0, 102));
        botaoCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoCliente.setForeground(new java.awt.Color(255, 255, 255));
        botaoCliente.setText("CLIENTE");
        jPanel1.add(botaoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 238, 115, -1));

        botaoFuncionarios.setBackground(new java.awt.Color(102, 0, 102));
        botaoFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        botaoFuncionarios.setText("FUNCIONÁRIOS");
        jPanel1.add(botaoFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        botaoPlanos.setBackground(new java.awt.Color(102, 0, 102));
        botaoPlanos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoPlanos.setForeground(new java.awt.Color(255, 255, 255));
        botaoPlanos.setText("PLANOS");
        jPanel1.add(botaoPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 238, 102, -1));

        botaoMaquinas.setBackground(new java.awt.Color(102, 0, 102));
        botaoMaquinas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoMaquinas.setForeground(new java.awt.Color(255, 255, 255));
        botaoMaquinas.setText("MÁQUINAS");
        jPanel1.add(botaoMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 463, 130, -1));

        botaoCaixa.setBackground(new java.awt.Color(102, 0, 102));
        botaoCaixa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoCaixa.setForeground(new java.awt.Color(255, 255, 255));
        botaoCaixa.setText("CAIXA");
        jPanel1.add(botaoCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 463, 102, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Cadastro (2).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("HOME ");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("CLIENTE");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("FUNCIONÁRIO");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("PLANOS");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("MÁQUINAS");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("CAIXA");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCaixa;
    private javax.swing.JButton botaoCliente;
    private javax.swing.JButton botaoFuncionarios;
    private javax.swing.JButton botaoIconeCaixa;
    private javax.swing.JButton botaoIconeCliente;
    private javax.swing.JButton botaoIconeFuncionarios;
    private javax.swing.JButton botaoIconeMaquinas;
    private javax.swing.JButton botaoIconePlanos;
    private javax.swing.JButton botaoMaquinas;
    private javax.swing.JButton botaoPlanos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
