/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class telaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastro1 = new javax.swing.JPanel();
        nomeCompleto = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        campoCpf = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        endereço = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        campoEndereço = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoCpf1 = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        nomeCompletocampo = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        butonDeCadastro = new javax.swing.JButton();
        cadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCadastro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeCompleto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        nomeCompleto.setText("Nome Completo:");
        painelCadastro1.add(nomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, -1));

        email.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        email.setText("E-mail:");
        painelCadastro1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        campoCpf.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        campoCpf.setText("CPF:");
        painelCadastro1.add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        telefone.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        telefone.setText("Telefone:");
        painelCadastro1.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        endereço.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        endereço.setText("Endereço:");
        painelCadastro1.add(endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        senha.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        senha.setText("Senha");
        painelCadastro1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        campoEndereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEndereçoActionPerformed(evt);
            }
        });
        painelCadastro1.add(campoEndereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 340, 30));

        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });
        painelCadastro1.add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 340, -1));
        painelCadastro1.add(campoCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 340, -1));

        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        painelCadastro1.add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 340, -1));
        painelCadastro1.add(nomeCompletocampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 340, -1));

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        painelCadastro1.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 340, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelCadastro1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 340, -1));

        butonDeCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butonDeCadastro.setText("Cadastra");
        butonDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonDeCadastroActionPerformed(evt);
            }
        });
        painelCadastro1.add(butonDeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 100, 40));

        cadastro.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\NewBitNexus\\BitNexus\\src\\main\\java\\img\\Cadastro (2).png")); // NOI18N
        painelCadastro1.add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1040, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEndereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEndereçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEndereçoActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void butonDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonDeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonDeCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonDeCadastro;
    private javax.swing.JLabel cadastro;
    private javax.swing.JLabel campoCpf;
    private javax.swing.JTextField campoCpf1;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereço;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereço;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel nomeCompleto;
    private javax.swing.JTextField nomeCompletocampo;
    private javax.swing.JPanel painelCadastro1;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
